# Generated by Django 4.2.1 on 2023-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_uploadedphoto_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedphoto",
            name="file",
            field=models.ImageField(upload_to="image/"),
        ),
    ]
